import {useRouter} from 'next/router'
import {Rubik} from 'next/font/google' // Assuming you need these imports in _app.js
import './globals.css'
import Nav from '@/components/shared/Nav'
import RootLayout from './layout' // Import your RootLayout component

const rubikRegular = Rubik({
  // Font configuration
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function MyApp({Component, pageProps}) {
  const router = useRouter()

  return (
    <RootLayout>
      {' '}
      {/* Use your RootLayout component */}
      <div key={router.route}>
        <Nav /> {/* Navigation component */}
        <Component {...pageProps} /> {/* Render the actual page component */}
      </div>
    </RootLayout>
  )
}
