import {Rubik} from 'next/font/google'
import './globals.css'
import Nav from '@/components/shared/Nav'

// app/layout.jsx
import {UserProvider} from '@auth0/nextjs-auth0/client'

const rubikRegular = Rubik({
  subsets: ['latin'],
  variable: '--font-rubik',
  weight: ['400'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <UserProvider>
        <head>
          <title>W4Kitchen</title>
        </head>

        <body
          className={`${rubikRegular.variable} flex flex-col bg-page font-rubik`}>
          <Nav />
          {children}
        </body>
      </UserProvider>
    </html>
  )
}
