import {Inter} from 'next/font/google'
import './globals.css'
import Nav from '@/components/shared/Nav'
import Logo from '@/components/shared/Logo'

const inter = Inter({subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {
  return (
    <main className={'flex flex-col'}>
      <Nav />
      <div className={inter.className}>{children}</div>
    </main>
  )
}
